parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_postgresql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geography:
                class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
                commented: false
            geometry:
                class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
                commented: false
            raster:
                class: 'Jsor\Doctrine\PostGIS\Types\RasterType'
                commented: false
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.apcu_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.apcu_cache_provider
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                regexp_replace: DoctrineExtensions\Query\Postgresql\RegexpReplace

services:
    doctrine.apcu_cache_provider:
        class: Doctrine\Common\Cache\ApcuCache
        public: false
