# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    disable_csrf_role: ROLE_ADMIN
    allowed_methods_listener: true
    param_fetcher_listener:
        enabled: true
        force: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: ['html'], fallback_format: 'json' }
    versioning: true
    view:
        formats:
            json: ~
        view_response_listener: 'force'
    routing_loader:
        default_format: json
