monolog:
    channels: [api_warning, api_mercure]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        api_warning:
            type: stream
            path: "%kernel.logs_dir%/api/%kernel.environment%.log"
            level: debug
            channels: api_warning
        api_mercure:
            type: stream
            path: "%kernel.logs_dir%/api/mercure_%kernel.environment%.log"
            level: debug
            channels: api_mercure
